// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  DeleteRolesByIdData,
  DeleteRolesByIdResponses,
  GetHealthLivezData,
  GetHealthLivezResponses,
  GetHealthReadyzData,
  GetHealthReadyzErrors,
  GetHealthReadyzResponses,
  GetRedirectByInstitutionIdData,
  GetRedirectByInstitutionIdErrors,
  GetRolesByIdData,
  GetRolesByIdResponses,
  GetRolesData,
  GetRolesPermissionsData,
  GetRolesPermissionsResponses,
  GetRolesResponses,
  GetUsersData,
  GetUsersMeData,
  GetUsersMeResponses,
  GetUsersResponses,
  PatchUsersByIdStatusData,
  PatchUsersByIdStatusResponses,
  PostRolesData,
  PostRolesResponses,
  PostUsersByIdRolesData,
  PostUsersByIdRolesResponses,
  PostUsersData,
  PostUsersResponses,
  PutRolesByIdData,
  PutRolesByIdResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Liveness Probe
 *
 * Check if the application is running. Used by Kubernetes to restart the container if it hangs.
 */
export const getHealthLivez = <ThrowOnError extends boolean = false>(
  options?: Options<GetHealthLivezData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetHealthLivezResponses,
    unknown,
    ThrowOnError
  >({ url: "/health/livez", ...options });

/**
 * Readiness Probe
 *
 * Check if the application is ready to accept traffic. Checks database and cache connectivity.
 */
export const getHealthReadyz = <ThrowOnError extends boolean = false>(
  options?: Options<GetHealthReadyzData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetHealthReadyzResponses,
    GetHealthReadyzErrors,
    ThrowOnError
  >({ url: "/health/readyz", ...options });

/**
 * Handle IDP Redirect
 *
 * Handles the redirect flow from an Identity Provider. Validates the token, creates a session, and redirects the user.
 */
export const getRedirectByInstitutionId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetRedirectByInstitutionIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    unknown,
    GetRedirectByInstitutionIdErrors,
    ThrowOnError
  >({ url: "/redirect/{institution_id}", ...options });

/**
 * List Roles
 */
export const getRoles = <ThrowOnError extends boolean = false>(
  options?: Options<GetRolesData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetRolesResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/roles",
    ...options,
  });

/**
 * Create Role
 */
export const postRoles = <ThrowOnError extends boolean = false>(
  options: Options<PostRolesData, ThrowOnError>
) =>
  (options.client ?? client).post<PostRolesResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/roles",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Role
 */
export const deleteRolesById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteRolesByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteRolesByIdResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/roles/{id}",
    ...options,
  });

/**
 * Get Role by ID
 */
export const getRolesById = <ThrowOnError extends boolean = false>(
  options: Options<GetRolesByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<GetRolesByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/roles/{id}",
    ...options,
  });

/**
 * Update Role
 */
export const putRolesById = <ThrowOnError extends boolean = false>(
  options: Options<PutRolesByIdData, ThrowOnError>
) =>
  (options.client ?? client).put<PutRolesByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/roles/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Permissions
 */
export const getRolesPermissions = <ThrowOnError extends boolean = false>(
  options?: Options<GetRolesPermissionsData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetRolesPermissionsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/roles/permissions",
    ...options,
  });

/**
 * Get Current User Profile
 *
 * Retrieve the profile and authorization details of the currently authenticated user.
 */
export const getUsersMe = <ThrowOnError extends boolean = false>(
  options?: Options<GetUsersMeData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetUsersMeResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me",
    ...options,
  });

/**
 * List Users
 */
export const getUsers = <ThrowOnError extends boolean = false>(
  options?: Options<GetUsersData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetUsersResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users",
    ...options,
  });

/**
 * Sync User
 *
 * Synchronize user data using IDP access token.
 */
export const postUsers = <ThrowOnError extends boolean = false>(
  options: Options<PostUsersData, ThrowOnError>
) =>
  (options.client ?? client).post<PostUsersResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update User Status
 */
export const patchUsersByIdStatus = <ThrowOnError extends boolean = false>(
  options: Options<PatchUsersByIdStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchUsersByIdStatusResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}/status",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Assign Roles to User
 */
export const postUsersByIdRoles = <ThrowOnError extends boolean = false>(
  options: Options<PostUsersByIdRolesData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostUsersByIdRolesResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}/roles",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
