// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8080" | (string & {});
};

export type Response = {
  success?: boolean;
  message?: string;
  data?: {
    [key: string]: unknown;
  } | null;
  meta?: Meta;
  error?: Error;
};

export type Meta = {
  page?: number;
  size?: number;
  total?: number;
  total_pages?: number;
};

export type Error = {
  code?: string;
  message?: string;
};

export type Permission = {
  id?: string;
  code?: string;
  name?: string;
  description?: string;
};

export type Role = {
  id?: string;
  name?: string;
  description?: string;
  permissions?: Array<Permission>;
};

export type User = {
  id?: string;
  username?: string;
  email?: string;
  institution_id?: string;
  status?: "active" | "inactive";
};

export type UserRoleAssignment = {
  role_id?: string;
  role_name?: string;
  groups?: Array<string>;
  permissions?: Array<string>;
};

export type Me = {
  id?: string;
  institution_id?: string;
  external_subject?: string;
  status?: string;
  metadata?: {
    [key: string]: unknown;
  };
  roles?: Array<UserRoleAssignment>;
  groups?: Array<string>;
  permissions?: Array<string>;
};

export type CreateRoleRequest = {
  name: string;
  description?: string;
  permissions: Array<string>;
};

export type UpdateRoleRequest = {
  name?: string;
  description?: string;
  permissions?: Array<string>;
};

export type SyncUserRequest = {
  access_token: string;
};

export type UpdateUserStatusRequest = {
  status: "active" | "inactive";
};

export type AssignRoleRequest = {
  roles: Array<string>;
};

export type GetHealthLivezData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health/livez";
};

export type GetHealthLivezResponses = {
  /**
   * Application is alive.
   */
  200: unknown;
};

export type GetHealthReadyzData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health/readyz";
};

export type GetHealthReadyzErrors = {
  /**
   * Application is not ready (dependency failure).
   */
  503: unknown;
};

export type GetHealthReadyzResponses = {
  /**
   * Application is ready.
   */
  200: unknown;
};

export type GetRedirectByInstitutionIdData = {
  body?: never;
  path: {
    /**
     * ID of the institution
     */
    institution_id: string;
  };
  query: {
    /**
     * IDP access token
     */
    token: string;
  };
  url: "/redirect/{institution_id}";
};

export type GetRedirectByInstitutionIdErrors = {
  /**
   * Bad Request (missing params)
   */
  400: unknown;
  /**
   * Forbidden (invalid token)
   */
  403: unknown;
  /**
   * Not Found (institution or user)
   */
  404: unknown;
};

export type GetRolesData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    size?: number;
    /**
     * Search term for role name
     */
    query?: string;
  };
  url: "/roles";
};

export type GetRolesResponses = {
  /**
   * List of roles with pagination
   */
  200: Response & {
    data?: Array<Role>;
  };
};

export type GetRolesResponse = GetRolesResponses[keyof GetRolesResponses];

export type PostRolesData = {
  body: CreateRoleRequest;
  path?: never;
  query?: never;
  url: "/roles";
};

export type PostRolesResponses = {
  /**
   * Role created successfully
   */
  201: Response & {
    data?: Role;
  };
};

export type PostRolesResponse = PostRolesResponses[keyof PostRolesResponses];

export type DeleteRolesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/roles/{id}";
};

export type DeleteRolesByIdResponses = {
  /**
   * Role deleted successfully
   */
  200: Response;
};

export type DeleteRolesByIdResponse =
  DeleteRolesByIdResponses[keyof DeleteRolesByIdResponses];

export type GetRolesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/roles/{id}";
};

export type GetRolesByIdResponses = {
  /**
   * Role details
   */
  200: Response & {
    data?: Role;
  };
};

export type GetRolesByIdResponse =
  GetRolesByIdResponses[keyof GetRolesByIdResponses];

export type PutRolesByIdData = {
  body: UpdateRoleRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/roles/{id}";
};

export type PutRolesByIdResponses = {
  /**
   * Role updated successfully
   */
  200: Response & {
    data?: Role;
  };
};

export type PutRolesByIdResponse =
  PutRolesByIdResponses[keyof PutRolesByIdResponses];

export type GetRolesPermissionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/roles/permissions";
};

export type GetRolesPermissionsResponses = {
  /**
   * List of available permissions
   */
  200: Response & {
    data?: Array<Permission>;
  };
};

export type GetRolesPermissionsResponse =
  GetRolesPermissionsResponses[keyof GetRolesPermissionsResponses];

export type GetUsersMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/me";
};

export type GetUsersMeResponses = {
  /**
   * User profile retrieved
   */
  200: Response & {
    data?: Me;
  };
};

export type GetUsersMeResponse = GetUsersMeResponses[keyof GetUsersMeResponses];

export type GetUsersData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    size?: number;
    /**
     * Search term for user
     */
    query?: string;
  };
  url: "/users";
};

export type GetUsersResponses = {
  /**
   * List of users with pagination
   */
  200: Response & {
    data?: Array<User>;
  };
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type PostUsersData = {
  body: SyncUserRequest;
  path?: never;
  query?: never;
  url: "/users";
};

export type PostUsersResponses = {
  /**
   * User synced successfully
   */
  200: Response & {
    data?: User;
  };
};

export type PostUsersResponse = PostUsersResponses[keyof PostUsersResponses];

export type PatchUsersByIdStatusData = {
  body: UpdateUserStatusRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/users/{id}/status";
};

export type PatchUsersByIdStatusResponses = {
  /**
   * User status updated successfully
   */
  200: Response;
};

export type PatchUsersByIdStatusResponse =
  PatchUsersByIdStatusResponses[keyof PatchUsersByIdStatusResponses];

export type PostUsersByIdRolesData = {
  body: AssignRoleRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/users/{id}/roles";
};

export type PostUsersByIdRolesResponses = {
  /**
   * Roles assigned successfully
   */
  200: Response;
};

export type PostUsersByIdRolesResponse =
  PostUsersByIdRolesResponses[keyof PostUsersByIdRolesResponses];
