// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  deleteRolesById,
  getHealthLivez,
  getHealthReadyz,
  getRedirectByInstitutionId,
  getRoles,
  getRolesById,
  getRolesPermissions,
  getUsers,
  getUsersMe,
  type Options,
  patchUsersByIdStatus,
  postRoles,
  postUsers,
  postUsersByIdRoles,
  putRolesById,
} from "../sdk.gen";
import type {
  DeleteRolesByIdData,
  DeleteRolesByIdResponse,
  GetHealthLivezData,
  GetHealthReadyzData,
  GetRedirectByInstitutionIdData,
  GetRolesByIdData,
  GetRolesByIdResponse,
  GetRolesData,
  GetRolesPermissionsData,
  GetRolesPermissionsResponse,
  GetRolesResponse,
  GetUsersData,
  GetUsersMeData,
  GetUsersMeResponse,
  GetUsersResponse,
  PatchUsersByIdStatusData,
  PatchUsersByIdStatusResponse,
  PostRolesData,
  PostRolesResponse,
  PostUsersByIdRolesData,
  PostUsersByIdRolesResponse,
  PostUsersData,
  PostUsersResponse,
  PutRolesByIdData,
  PutRolesByIdResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getHealthLivezQueryKey = (options?: Options<GetHealthLivezData>) =>
  createQueryKey("getHealthLivez", options);

/**
 * Liveness Probe
 *
 * Check if the application is running. Used by Kubernetes to restart the container if it hangs.
 */
export const getHealthLivezOptions = (options?: Options<GetHealthLivezData>) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof getHealthLivezQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHealthLivez({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHealthLivezQueryKey(options),
  });

export const getHealthReadyzQueryKey = (
  options?: Options<GetHealthReadyzData>
) => createQueryKey("getHealthReadyz", options);

/**
 * Readiness Probe
 *
 * Check if the application is ready to accept traffic. Checks database and cache connectivity.
 */
export const getHealthReadyzOptions = (
  options?: Options<GetHealthReadyzData>
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof getHealthReadyzQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHealthReadyz({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHealthReadyzQueryKey(options),
  });

export const getRedirectByInstitutionIdQueryKey = (
  options: Options<GetRedirectByInstitutionIdData>
) => createQueryKey("getRedirectByInstitutionId", options);

/**
 * Handle IDP Redirect
 *
 * Handles the redirect flow from an Identity Provider. Validates the token, creates a session, and redirects the user.
 */
export const getRedirectByInstitutionIdOptions = (
  options: Options<GetRedirectByInstitutionIdData>
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof getRedirectByInstitutionIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRedirectByInstitutionId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRedirectByInstitutionIdQueryKey(options),
  });

export const getRolesQueryKey = (options?: Options<GetRolesData>) =>
  createQueryKey("getRoles", options);

/**
 * List Roles
 */
export const getRolesOptions = (options?: Options<GetRolesData>) =>
  queryOptions<
    GetRolesResponse,
    DefaultError,
    GetRolesResponse,
    ReturnType<typeof getRolesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRoles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRolesQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const getRolesInfiniteQueryKey = (
  options?: Options<GetRolesData>
): QueryKey<Options<GetRolesData>> => createQueryKey("getRoles", options, true);

/**
 * List Roles
 */
export const getRolesInfiniteOptions = (options?: Options<GetRolesData>) =>
  infiniteQueryOptions<
    GetRolesResponse,
    DefaultError,
    InfiniteData<GetRolesResponse>,
    QueryKey<Options<GetRolesData>>,
    | number
    | Pick<
        QueryKey<Options<GetRolesData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetRolesData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getRoles({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getRolesInfiniteQueryKey(options),
    }
  );

/**
 * Create Role
 */
export const postRolesMutation = (
  options?: Partial<Options<PostRolesData>>
): UseMutationOptions<
  PostRolesResponse,
  DefaultError,
  Options<PostRolesData>
> => {
  const mutationOptions: UseMutationOptions<
    PostRolesResponse,
    DefaultError,
    Options<PostRolesData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postRoles({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Role
 */
export const deleteRolesByIdMutation = (
  options?: Partial<Options<DeleteRolesByIdData>>
): UseMutationOptions<
  DeleteRolesByIdResponse,
  DefaultError,
  Options<DeleteRolesByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteRolesByIdResponse,
    DefaultError,
    Options<DeleteRolesByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteRolesById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getRolesByIdQueryKey = (options: Options<GetRolesByIdData>) =>
  createQueryKey("getRolesById", options);

/**
 * Get Role by ID
 */
export const getRolesByIdOptions = (options: Options<GetRolesByIdData>) =>
  queryOptions<
    GetRolesByIdResponse,
    DefaultError,
    GetRolesByIdResponse,
    ReturnType<typeof getRolesByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRolesById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRolesByIdQueryKey(options),
  });

/**
 * Update Role
 */
export const putRolesByIdMutation = (
  options?: Partial<Options<PutRolesByIdData>>
): UseMutationOptions<
  PutRolesByIdResponse,
  DefaultError,
  Options<PutRolesByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutRolesByIdResponse,
    DefaultError,
    Options<PutRolesByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putRolesById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getRolesPermissionsQueryKey = (
  options?: Options<GetRolesPermissionsData>
) => createQueryKey("getRolesPermissions", options);

/**
 * List Permissions
 */
export const getRolesPermissionsOptions = (
  options?: Options<GetRolesPermissionsData>
) =>
  queryOptions<
    GetRolesPermissionsResponse,
    DefaultError,
    GetRolesPermissionsResponse,
    ReturnType<typeof getRolesPermissionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRolesPermissions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRolesPermissionsQueryKey(options),
  });

export const getUsersMeQueryKey = (options?: Options<GetUsersMeData>) =>
  createQueryKey("getUsersMe", options);

/**
 * Get Current User Profile
 *
 * Retrieve the profile and authorization details of the currently authenticated user.
 */
export const getUsersMeOptions = (options?: Options<GetUsersMeData>) =>
  queryOptions<
    GetUsersMeResponse,
    DefaultError,
    GetUsersMeResponse,
    ReturnType<typeof getUsersMeQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUsersMe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUsersMeQueryKey(options),
  });

export const getUsersQueryKey = (options?: Options<GetUsersData>) =>
  createQueryKey("getUsers", options);

/**
 * List Users
 */
export const getUsersOptions = (options?: Options<GetUsersData>) =>
  queryOptions<
    GetUsersResponse,
    DefaultError,
    GetUsersResponse,
    ReturnType<typeof getUsersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUsersQueryKey(options),
  });

export const getUsersInfiniteQueryKey = (
  options?: Options<GetUsersData>
): QueryKey<Options<GetUsersData>> => createQueryKey("getUsers", options, true);

/**
 * List Users
 */
export const getUsersInfiniteOptions = (options?: Options<GetUsersData>) =>
  infiniteQueryOptions<
    GetUsersResponse,
    DefaultError,
    InfiniteData<GetUsersResponse>,
    QueryKey<Options<GetUsersData>>,
    | number
    | Pick<
        QueryKey<Options<GetUsersData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetUsersData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getUsers({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getUsersInfiniteQueryKey(options),
    }
  );

/**
 * Sync User
 *
 * Synchronize user data using IDP access token.
 */
export const postUsersMutation = (
  options?: Partial<Options<PostUsersData>>
): UseMutationOptions<
  PostUsersResponse,
  DefaultError,
  Options<PostUsersData>
> => {
  const mutationOptions: UseMutationOptions<
    PostUsersResponse,
    DefaultError,
    Options<PostUsersData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postUsers({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update User Status
 */
export const patchUsersByIdStatusMutation = (
  options?: Partial<Options<PatchUsersByIdStatusData>>
): UseMutationOptions<
  PatchUsersByIdStatusResponse,
  DefaultError,
  Options<PatchUsersByIdStatusData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchUsersByIdStatusResponse,
    DefaultError,
    Options<PatchUsersByIdStatusData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchUsersByIdStatus({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Assign Roles to User
 */
export const postUsersByIdRolesMutation = (
  options?: Partial<Options<PostUsersByIdRolesData>>
): UseMutationOptions<
  PostUsersByIdRolesResponse,
  DefaultError,
  Options<PostUsersByIdRolesData>
> => {
  const mutationOptions: UseMutationOptions<
    PostUsersByIdRolesResponse,
    DefaultError,
    Options<PostUsersByIdRolesData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postUsersByIdRoles({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
