// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://centraldev-api.universitaspertamina.ac.id" | (string & {});
};

export type LoginRequest = {
  username: string;
  password: string;
};

export type LoginResponse = {
  success?: boolean;
  access_token?: string;
  token_type?: string;
  expires_in?: number;
  formatted_expires_in?: string;
};

export type PostAuthLoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: "/api/v1/auth/login";
};

export type LoginErrorResponse = {
  success?: boolean;
  message?: string;
  url?: string;
  method?: string;
  timestamp?: string;
};

export type PostAuthLoginResponses = {
  /**
   * Login successful
   */
  200: LoginResponse;
};

export type PostAuthLoginErrors = {
  /**
   * Invalid credentials
   */
  401: LoginErrorResponse;
};

export type PostAuthLoginResponse =
  PostAuthLoginResponses[keyof PostAuthLoginResponses];
