// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { type Options, postAuthLogin } from "../sdk.gen";
import type { PostAuthLoginData, PostAuthLoginResponse } from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

/**
 * Login
 */
export const postAuthLoginMutation = (
  options?: Partial<Options<PostAuthLoginData>>
): UseMutationOptions<
  PostAuthLoginResponse,
  DefaultError,
  Options<PostAuthLoginData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAuthLoginResponse,
    DefaultError,
    Options<PostAuthLoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postAuthLogin({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
