/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutRoomAssetListRouteImport } from './routes/_layout/room-asset-list'
import { Route as LayoutRoomAssetListIdRouteImport } from './routes/_layout/room-asset-list.$id'
import { Route as LayoutLecturerScanRouteImport } from './routes/_layout/lecturer/scan'
import { Route as LayoutLecturerRoomAssetListRouteImport } from './routes/_layout/lecturer/room-asset-list'
import { Route as LayoutLecturerReportSuccessRouteImport } from './routes/_layout/lecturer/report-success'
import { Route as LayoutLecturerMyReportRouteImport } from './routes/_layout/lecturer/my-report'
import { Route as LayoutLecturerHomeRouteImport } from './routes/_layout/lecturer/home'
import { Route as LayoutHousekeepingScanRouteImport } from './routes/_layout/housekeeping/scan'
import { Route as LayoutHousekeepingReportHistoryRouteImport } from './routes/_layout/housekeeping/report-history'
import { Route as LayoutHousekeepingChecklistDashboardRouteImport } from './routes/_layout/housekeeping/checklist-dashboard'
import { Route as LayoutFmItTicketListRouteImport } from './routes/_layout/fm-it/ticket-list'
import { Route as LayoutFmItNotificationRouteImport } from './routes/_layout/fm-it/notification'
import { Route as LayoutFmItHomeRouteImport } from './routes/_layout/fm-it/home'
import { Route as LayoutLecturerRoomAssetListIdRouteImport } from './routes/_layout/lecturer/room-asset-list.$id'
import { Route as LayoutLecturerReportSuccessIdRouteImport } from './routes/_layout/lecturer/report-success.$id'
import { Route as LayoutLecturerReportDetailPageIdRouteImport } from './routes/_layout/lecturer/report-detail-page.$id'
import { Route as LayoutHousekeepingRoomChecklistIdRouteImport } from './routes/_layout/housekeeping/room-checklist.$id'
import { Route as LayoutHousekeepingChecklistReportIdRouteImport } from './routes/_layout/housekeeping/checklist-report.$id'
import { Route as LayoutFmItTicketDetailIdRouteImport } from './routes/_layout/fm-it/ticket-detail.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRoomAssetListRoute = LayoutRoomAssetListRouteImport.update({
  id: '/room-asset-list',
  path: '/room-asset-list',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRoomAssetListIdRoute = LayoutRoomAssetListIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutRoomAssetListRoute,
} as any)
const LayoutLecturerScanRoute = LayoutLecturerScanRouteImport.update({
  id: '/lecturer/scan',
  path: '/lecturer/scan',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLecturerRoomAssetListRoute =
  LayoutLecturerRoomAssetListRouteImport.update({
    id: '/lecturer/room-asset-list',
    path: '/lecturer/room-asset-list',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutLecturerReportSuccessRoute =
  LayoutLecturerReportSuccessRouteImport.update({
    id: '/lecturer/report-success',
    path: '/lecturer/report-success',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutLecturerMyReportRoute = LayoutLecturerMyReportRouteImport.update({
  id: '/lecturer/my-report',
  path: '/lecturer/my-report',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLecturerHomeRoute = LayoutLecturerHomeRouteImport.update({
  id: '/lecturer/home',
  path: '/lecturer/home',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHousekeepingScanRoute = LayoutHousekeepingScanRouteImport.update({
  id: '/housekeeping/scan',
  path: '/housekeeping/scan',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHousekeepingReportHistoryRoute =
  LayoutHousekeepingReportHistoryRouteImport.update({
    id: '/housekeeping/report-history',
    path: '/housekeeping/report-history',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutHousekeepingChecklistDashboardRoute =
  LayoutHousekeepingChecklistDashboardRouteImport.update({
    id: '/housekeeping/checklist-dashboard',
    path: '/housekeeping/checklist-dashboard',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutFmItTicketListRoute = LayoutFmItTicketListRouteImport.update({
  id: '/fm-it/ticket-list',
  path: '/fm-it/ticket-list',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFmItNotificationRoute = LayoutFmItNotificationRouteImport.update({
  id: '/fm-it/notification',
  path: '/fm-it/notification',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFmItHomeRoute = LayoutFmItHomeRouteImport.update({
  id: '/fm-it/home',
  path: '/fm-it/home',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLecturerRoomAssetListIdRoute =
  LayoutLecturerRoomAssetListIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => LayoutLecturerRoomAssetListRoute,
  } as any)
const LayoutLecturerReportSuccessIdRoute =
  LayoutLecturerReportSuccessIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => LayoutLecturerReportSuccessRoute,
  } as any)
const LayoutLecturerReportDetailPageIdRoute =
  LayoutLecturerReportDetailPageIdRouteImport.update({
    id: '/lecturer/report-detail-page/$id',
    path: '/lecturer/report-detail-page/$id',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutHousekeepingRoomChecklistIdRoute =
  LayoutHousekeepingRoomChecklistIdRouteImport.update({
    id: '/housekeeping/room-checklist/$id',
    path: '/housekeeping/room-checklist/$id',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutHousekeepingChecklistReportIdRoute =
  LayoutHousekeepingChecklistReportIdRouteImport.update({
    id: '/housekeeping/checklist-report/$id',
    path: '/housekeeping/checklist-report/$id',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutFmItTicketDetailIdRoute =
  LayoutFmItTicketDetailIdRouteImport.update({
    id: '/fm-it/ticket-detail/$id',
    path: '/fm-it/ticket-detail/$id',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/room-asset-list': typeof LayoutRoomAssetListRouteWithChildren
  '/fm-it/home': typeof LayoutFmItHomeRoute
  '/fm-it/notification': typeof LayoutFmItNotificationRoute
  '/fm-it/ticket-list': typeof LayoutFmItTicketListRoute
  '/housekeeping/checklist-dashboard': typeof LayoutHousekeepingChecklistDashboardRoute
  '/housekeeping/report-history': typeof LayoutHousekeepingReportHistoryRoute
  '/housekeeping/scan': typeof LayoutHousekeepingScanRoute
  '/lecturer/home': typeof LayoutLecturerHomeRoute
  '/lecturer/my-report': typeof LayoutLecturerMyReportRoute
  '/lecturer/report-success': typeof LayoutLecturerReportSuccessRouteWithChildren
  '/lecturer/room-asset-list': typeof LayoutLecturerRoomAssetListRouteWithChildren
  '/lecturer/scan': typeof LayoutLecturerScanRoute
  '/room-asset-list/$id': typeof LayoutRoomAssetListIdRoute
  '/fm-it/ticket-detail/$id': typeof LayoutFmItTicketDetailIdRoute
  '/housekeeping/checklist-report/$id': typeof LayoutHousekeepingChecklistReportIdRoute
  '/housekeeping/room-checklist/$id': typeof LayoutHousekeepingRoomChecklistIdRoute
  '/lecturer/report-detail-page/$id': typeof LayoutLecturerReportDetailPageIdRoute
  '/lecturer/report-success/$id': typeof LayoutLecturerReportSuccessIdRoute
  '/lecturer/room-asset-list/$id': typeof LayoutLecturerRoomAssetListIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/room-asset-list': typeof LayoutRoomAssetListRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/fm-it/home': typeof LayoutFmItHomeRoute
  '/fm-it/notification': typeof LayoutFmItNotificationRoute
  '/fm-it/ticket-list': typeof LayoutFmItTicketListRoute
  '/housekeeping/checklist-dashboard': typeof LayoutHousekeepingChecklistDashboardRoute
  '/housekeeping/report-history': typeof LayoutHousekeepingReportHistoryRoute
  '/housekeeping/scan': typeof LayoutHousekeepingScanRoute
  '/lecturer/home': typeof LayoutLecturerHomeRoute
  '/lecturer/my-report': typeof LayoutLecturerMyReportRoute
  '/lecturer/report-success': typeof LayoutLecturerReportSuccessRouteWithChildren
  '/lecturer/room-asset-list': typeof LayoutLecturerRoomAssetListRouteWithChildren
  '/lecturer/scan': typeof LayoutLecturerScanRoute
  '/room-asset-list/$id': typeof LayoutRoomAssetListIdRoute
  '/fm-it/ticket-detail/$id': typeof LayoutFmItTicketDetailIdRoute
  '/housekeeping/checklist-report/$id': typeof LayoutHousekeepingChecklistReportIdRoute
  '/housekeeping/room-checklist/$id': typeof LayoutHousekeepingRoomChecklistIdRoute
  '/lecturer/report-detail-page/$id': typeof LayoutLecturerReportDetailPageIdRoute
  '/lecturer/report-success/$id': typeof LayoutLecturerReportSuccessIdRoute
  '/lecturer/room-asset-list/$id': typeof LayoutLecturerRoomAssetListIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/room-asset-list': typeof LayoutRoomAssetListRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/fm-it/home': typeof LayoutFmItHomeRoute
  '/_layout/fm-it/notification': typeof LayoutFmItNotificationRoute
  '/_layout/fm-it/ticket-list': typeof LayoutFmItTicketListRoute
  '/_layout/housekeeping/checklist-dashboard': typeof LayoutHousekeepingChecklistDashboardRoute
  '/_layout/housekeeping/report-history': typeof LayoutHousekeepingReportHistoryRoute
  '/_layout/housekeeping/scan': typeof LayoutHousekeepingScanRoute
  '/_layout/lecturer/home': typeof LayoutLecturerHomeRoute
  '/_layout/lecturer/my-report': typeof LayoutLecturerMyReportRoute
  '/_layout/lecturer/report-success': typeof LayoutLecturerReportSuccessRouteWithChildren
  '/_layout/lecturer/room-asset-list': typeof LayoutLecturerRoomAssetListRouteWithChildren
  '/_layout/lecturer/scan': typeof LayoutLecturerScanRoute
  '/_layout/room-asset-list/$id': typeof LayoutRoomAssetListIdRoute
  '/_layout/fm-it/ticket-detail/$id': typeof LayoutFmItTicketDetailIdRoute
  '/_layout/housekeeping/checklist-report/$id': typeof LayoutHousekeepingChecklistReportIdRoute
  '/_layout/housekeeping/room-checklist/$id': typeof LayoutHousekeepingRoomChecklistIdRoute
  '/_layout/lecturer/report-detail-page/$id': typeof LayoutLecturerReportDetailPageIdRoute
  '/_layout/lecturer/report-success/$id': typeof LayoutLecturerReportSuccessIdRoute
  '/_layout/lecturer/room-asset-list/$id': typeof LayoutLecturerRoomAssetListIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/room-asset-list'
    | '/fm-it/home'
    | '/fm-it/notification'
    | '/fm-it/ticket-list'
    | '/housekeeping/checklist-dashboard'
    | '/housekeeping/report-history'
    | '/housekeeping/scan'
    | '/lecturer/home'
    | '/lecturer/my-report'
    | '/lecturer/report-success'
    | '/lecturer/room-asset-list'
    | '/lecturer/scan'
    | '/room-asset-list/$id'
    | '/fm-it/ticket-detail/$id'
    | '/housekeeping/checklist-report/$id'
    | '/housekeeping/room-checklist/$id'
    | '/lecturer/report-detail-page/$id'
    | '/lecturer/report-success/$id'
    | '/lecturer/room-asset-list/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/room-asset-list'
    | '/'
    | '/fm-it/home'
    | '/fm-it/notification'
    | '/fm-it/ticket-list'
    | '/housekeeping/checklist-dashboard'
    | '/housekeeping/report-history'
    | '/housekeeping/scan'
    | '/lecturer/home'
    | '/lecturer/my-report'
    | '/lecturer/report-success'
    | '/lecturer/room-asset-list'
    | '/lecturer/scan'
    | '/room-asset-list/$id'
    | '/fm-it/ticket-detail/$id'
    | '/housekeeping/checklist-report/$id'
    | '/housekeeping/room-checklist/$id'
    | '/lecturer/report-detail-page/$id'
    | '/lecturer/report-success/$id'
    | '/lecturer/room-asset-list/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/room-asset-list'
    | '/_layout/'
    | '/_layout/fm-it/home'
    | '/_layout/fm-it/notification'
    | '/_layout/fm-it/ticket-list'
    | '/_layout/housekeeping/checklist-dashboard'
    | '/_layout/housekeeping/report-history'
    | '/_layout/housekeeping/scan'
    | '/_layout/lecturer/home'
    | '/_layout/lecturer/my-report'
    | '/_layout/lecturer/report-success'
    | '/_layout/lecturer/room-asset-list'
    | '/_layout/lecturer/scan'
    | '/_layout/room-asset-list/$id'
    | '/_layout/fm-it/ticket-detail/$id'
    | '/_layout/housekeeping/checklist-report/$id'
    | '/_layout/housekeeping/room-checklist/$id'
    | '/_layout/lecturer/report-detail-page/$id'
    | '/_layout/lecturer/report-success/$id'
    | '/_layout/lecturer/room-asset-list/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/room-asset-list': {
      id: '/_layout/room-asset-list'
      path: '/room-asset-list'
      fullPath: '/room-asset-list'
      preLoaderRoute: typeof LayoutRoomAssetListRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/room-asset-list/$id': {
      id: '/_layout/room-asset-list/$id'
      path: '/$id'
      fullPath: '/room-asset-list/$id'
      preLoaderRoute: typeof LayoutRoomAssetListIdRouteImport
      parentRoute: typeof LayoutRoomAssetListRoute
    }
    '/_layout/lecturer/scan': {
      id: '/_layout/lecturer/scan'
      path: '/lecturer/scan'
      fullPath: '/lecturer/scan'
      preLoaderRoute: typeof LayoutLecturerScanRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/lecturer/room-asset-list': {
      id: '/_layout/lecturer/room-asset-list'
      path: '/lecturer/room-asset-list'
      fullPath: '/lecturer/room-asset-list'
      preLoaderRoute: typeof LayoutLecturerRoomAssetListRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/lecturer/report-success': {
      id: '/_layout/lecturer/report-success'
      path: '/lecturer/report-success'
      fullPath: '/lecturer/report-success'
      preLoaderRoute: typeof LayoutLecturerReportSuccessRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/lecturer/my-report': {
      id: '/_layout/lecturer/my-report'
      path: '/lecturer/my-report'
      fullPath: '/lecturer/my-report'
      preLoaderRoute: typeof LayoutLecturerMyReportRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/lecturer/home': {
      id: '/_layout/lecturer/home'
      path: '/lecturer/home'
      fullPath: '/lecturer/home'
      preLoaderRoute: typeof LayoutLecturerHomeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/housekeeping/scan': {
      id: '/_layout/housekeeping/scan'
      path: '/housekeeping/scan'
      fullPath: '/housekeeping/scan'
      preLoaderRoute: typeof LayoutHousekeepingScanRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/housekeeping/report-history': {
      id: '/_layout/housekeeping/report-history'
      path: '/housekeeping/report-history'
      fullPath: '/housekeeping/report-history'
      preLoaderRoute: typeof LayoutHousekeepingReportHistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/housekeeping/checklist-dashboard': {
      id: '/_layout/housekeeping/checklist-dashboard'
      path: '/housekeeping/checklist-dashboard'
      fullPath: '/housekeeping/checklist-dashboard'
      preLoaderRoute: typeof LayoutHousekeepingChecklistDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fm-it/ticket-list': {
      id: '/_layout/fm-it/ticket-list'
      path: '/fm-it/ticket-list'
      fullPath: '/fm-it/ticket-list'
      preLoaderRoute: typeof LayoutFmItTicketListRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fm-it/notification': {
      id: '/_layout/fm-it/notification'
      path: '/fm-it/notification'
      fullPath: '/fm-it/notification'
      preLoaderRoute: typeof LayoutFmItNotificationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fm-it/home': {
      id: '/_layout/fm-it/home'
      path: '/fm-it/home'
      fullPath: '/fm-it/home'
      preLoaderRoute: typeof LayoutFmItHomeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/lecturer/room-asset-list/$id': {
      id: '/_layout/lecturer/room-asset-list/$id'
      path: '/$id'
      fullPath: '/lecturer/room-asset-list/$id'
      preLoaderRoute: typeof LayoutLecturerRoomAssetListIdRouteImport
      parentRoute: typeof LayoutLecturerRoomAssetListRoute
    }
    '/_layout/lecturer/report-success/$id': {
      id: '/_layout/lecturer/report-success/$id'
      path: '/$id'
      fullPath: '/lecturer/report-success/$id'
      preLoaderRoute: typeof LayoutLecturerReportSuccessIdRouteImport
      parentRoute: typeof LayoutLecturerReportSuccessRoute
    }
    '/_layout/lecturer/report-detail-page/$id': {
      id: '/_layout/lecturer/report-detail-page/$id'
      path: '/lecturer/report-detail-page/$id'
      fullPath: '/lecturer/report-detail-page/$id'
      preLoaderRoute: typeof LayoutLecturerReportDetailPageIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/housekeeping/room-checklist/$id': {
      id: '/_layout/housekeeping/room-checklist/$id'
      path: '/housekeeping/room-checklist/$id'
      fullPath: '/housekeeping/room-checklist/$id'
      preLoaderRoute: typeof LayoutHousekeepingRoomChecklistIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/housekeeping/checklist-report/$id': {
      id: '/_layout/housekeeping/checklist-report/$id'
      path: '/housekeeping/checklist-report/$id'
      fullPath: '/housekeeping/checklist-report/$id'
      preLoaderRoute: typeof LayoutHousekeepingChecklistReportIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fm-it/ticket-detail/$id': {
      id: '/_layout/fm-it/ticket-detail/$id'
      path: '/fm-it/ticket-detail/$id'
      fullPath: '/fm-it/ticket-detail/$id'
      preLoaderRoute: typeof LayoutFmItTicketDetailIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRoomAssetListRouteChildren {
  LayoutRoomAssetListIdRoute: typeof LayoutRoomAssetListIdRoute
}

const LayoutRoomAssetListRouteChildren: LayoutRoomAssetListRouteChildren = {
  LayoutRoomAssetListIdRoute: LayoutRoomAssetListIdRoute,
}

const LayoutRoomAssetListRouteWithChildren =
  LayoutRoomAssetListRoute._addFileChildren(LayoutRoomAssetListRouteChildren)

interface LayoutLecturerReportSuccessRouteChildren {
  LayoutLecturerReportSuccessIdRoute: typeof LayoutLecturerReportSuccessIdRoute
}

const LayoutLecturerReportSuccessRouteChildren: LayoutLecturerReportSuccessRouteChildren =
  {
    LayoutLecturerReportSuccessIdRoute: LayoutLecturerReportSuccessIdRoute,
  }

const LayoutLecturerReportSuccessRouteWithChildren =
  LayoutLecturerReportSuccessRoute._addFileChildren(
    LayoutLecturerReportSuccessRouteChildren,
  )

interface LayoutLecturerRoomAssetListRouteChildren {
  LayoutLecturerRoomAssetListIdRoute: typeof LayoutLecturerRoomAssetListIdRoute
}

const LayoutLecturerRoomAssetListRouteChildren: LayoutLecturerRoomAssetListRouteChildren =
  {
    LayoutLecturerRoomAssetListIdRoute: LayoutLecturerRoomAssetListIdRoute,
  }

const LayoutLecturerRoomAssetListRouteWithChildren =
  LayoutLecturerRoomAssetListRoute._addFileChildren(
    LayoutLecturerRoomAssetListRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutRoomAssetListRoute: typeof LayoutRoomAssetListRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutFmItHomeRoute: typeof LayoutFmItHomeRoute
  LayoutFmItNotificationRoute: typeof LayoutFmItNotificationRoute
  LayoutFmItTicketListRoute: typeof LayoutFmItTicketListRoute
  LayoutHousekeepingChecklistDashboardRoute: typeof LayoutHousekeepingChecklistDashboardRoute
  LayoutHousekeepingReportHistoryRoute: typeof LayoutHousekeepingReportHistoryRoute
  LayoutHousekeepingScanRoute: typeof LayoutHousekeepingScanRoute
  LayoutLecturerHomeRoute: typeof LayoutLecturerHomeRoute
  LayoutLecturerMyReportRoute: typeof LayoutLecturerMyReportRoute
  LayoutLecturerReportSuccessRoute: typeof LayoutLecturerReportSuccessRouteWithChildren
  LayoutLecturerRoomAssetListRoute: typeof LayoutLecturerRoomAssetListRouteWithChildren
  LayoutLecturerScanRoute: typeof LayoutLecturerScanRoute
  LayoutFmItTicketDetailIdRoute: typeof LayoutFmItTicketDetailIdRoute
  LayoutHousekeepingChecklistReportIdRoute: typeof LayoutHousekeepingChecklistReportIdRoute
  LayoutHousekeepingRoomChecklistIdRoute: typeof LayoutHousekeepingRoomChecklistIdRoute
  LayoutLecturerReportDetailPageIdRoute: typeof LayoutLecturerReportDetailPageIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutRoomAssetListRoute: LayoutRoomAssetListRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutFmItHomeRoute: LayoutFmItHomeRoute,
  LayoutFmItNotificationRoute: LayoutFmItNotificationRoute,
  LayoutFmItTicketListRoute: LayoutFmItTicketListRoute,
  LayoutHousekeepingChecklistDashboardRoute:
    LayoutHousekeepingChecklistDashboardRoute,
  LayoutHousekeepingReportHistoryRoute: LayoutHousekeepingReportHistoryRoute,
  LayoutHousekeepingScanRoute: LayoutHousekeepingScanRoute,
  LayoutLecturerHomeRoute: LayoutLecturerHomeRoute,
  LayoutLecturerMyReportRoute: LayoutLecturerMyReportRoute,
  LayoutLecturerReportSuccessRoute:
    LayoutLecturerReportSuccessRouteWithChildren,
  LayoutLecturerRoomAssetListRoute:
    LayoutLecturerRoomAssetListRouteWithChildren,
  LayoutLecturerScanRoute: LayoutLecturerScanRoute,
  LayoutFmItTicketDetailIdRoute: LayoutFmItTicketDetailIdRoute,
  LayoutHousekeepingChecklistReportIdRoute:
    LayoutHousekeepingChecklistReportIdRoute,
  LayoutHousekeepingRoomChecklistIdRoute:
    LayoutHousekeepingRoomChecklistIdRoute,
  LayoutLecturerReportDetailPageIdRoute: LayoutLecturerReportDetailPageIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
