/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutRoomAssetListRouteImport } from './routes/_layout/room-asset-list'
import { Route as LayoutHistoryRouteImport } from './routes/_layout/history'
import { Route as LayoutTicketIndexRouteImport } from './routes/_layout/ticket/index'
import { Route as LayoutScanIndexRouteImport } from './routes/_layout/scan/index'
import { Route as LayoutChecklistIndexRouteImport } from './routes/_layout/checklist/index'
import { Route as LayoutTicketIdRouteImport } from './routes/_layout/ticket/$id'
import { Route as LayoutRoomAssetListIdRouteImport } from './routes/_layout/room-asset-list.$id'
import { Route as LayoutLecturerRoomAssetListRouteImport } from './routes/_layout/lecturer/room-asset-list'
import { Route as LayoutFmItTicketListRouteImport } from './routes/_layout/fm-it/ticket-list'
import { Route as LayoutFmItNotificationRouteImport } from './routes/_layout/fm-it/notification'
import { Route as LayoutDailyCheckingIdRouteImport } from './routes/_layout/daily-checking/$id'
import { Route as LayoutChecklistIdRouteImport } from './routes/_layout/checklist/$id'
import { Route as LayoutModuleHomeRouteImport } from './routes/_layout/$module/home'
import { Route as LayoutLecturerRoomAssetListIdRouteImport } from './routes/_layout/lecturer/room-asset-list.$id'
import { Route as LayoutFmItTicketDetailIdRouteImport } from './routes/_layout/fm-it/ticket-detail.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRoomAssetListRoute = LayoutRoomAssetListRouteImport.update({
  id: '/room-asset-list',
  path: '/room-asset-list',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHistoryRoute = LayoutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTicketIndexRoute = LayoutTicketIndexRouteImport.update({
  id: '/ticket/',
  path: '/ticket/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutScanIndexRoute = LayoutScanIndexRouteImport.update({
  id: '/scan/',
  path: '/scan/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChecklistIndexRoute = LayoutChecklistIndexRouteImport.update({
  id: '/checklist/',
  path: '/checklist/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTicketIdRoute = LayoutTicketIdRouteImport.update({
  id: '/ticket/$id',
  path: '/ticket/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRoomAssetListIdRoute = LayoutRoomAssetListIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutRoomAssetListRoute,
} as any)
const LayoutLecturerRoomAssetListRoute =
  LayoutLecturerRoomAssetListRouteImport.update({
    id: '/lecturer/room-asset-list',
    path: '/lecturer/room-asset-list',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutFmItTicketListRoute = LayoutFmItTicketListRouteImport.update({
  id: '/fm-it/ticket-list',
  path: '/fm-it/ticket-list',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFmItNotificationRoute = LayoutFmItNotificationRouteImport.update({
  id: '/fm-it/notification',
  path: '/fm-it/notification',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDailyCheckingIdRoute = LayoutDailyCheckingIdRouteImport.update({
  id: '/daily-checking/$id',
  path: '/daily-checking/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChecklistIdRoute = LayoutChecklistIdRouteImport.update({
  id: '/checklist/$id',
  path: '/checklist/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutModuleHomeRoute = LayoutModuleHomeRouteImport.update({
  id: '/$module/home',
  path: '/$module/home',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLecturerRoomAssetListIdRoute =
  LayoutLecturerRoomAssetListIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => LayoutLecturerRoomAssetListRoute,
  } as any)
const LayoutFmItTicketDetailIdRoute =
  LayoutFmItTicketDetailIdRouteImport.update({
    id: '/fm-it/ticket-detail/$id',
    path: '/fm-it/ticket-detail/$id',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/history': typeof LayoutHistoryRoute
  '/room-asset-list': typeof LayoutRoomAssetListRouteWithChildren
  '/$module/home': typeof LayoutModuleHomeRoute
  '/checklist/$id': typeof LayoutChecklistIdRoute
  '/daily-checking/$id': typeof LayoutDailyCheckingIdRoute
  '/fm-it/notification': typeof LayoutFmItNotificationRoute
  '/fm-it/ticket-list': typeof LayoutFmItTicketListRoute
  '/lecturer/room-asset-list': typeof LayoutLecturerRoomAssetListRouteWithChildren
  '/room-asset-list/$id': typeof LayoutRoomAssetListIdRoute
  '/ticket/$id': typeof LayoutTicketIdRoute
  '/checklist/': typeof LayoutChecklistIndexRoute
  '/scan/': typeof LayoutScanIndexRoute
  '/ticket/': typeof LayoutTicketIndexRoute
  '/fm-it/ticket-detail/$id': typeof LayoutFmItTicketDetailIdRoute
  '/lecturer/room-asset-list/$id': typeof LayoutLecturerRoomAssetListIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/history': typeof LayoutHistoryRoute
  '/room-asset-list': typeof LayoutRoomAssetListRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/$module/home': typeof LayoutModuleHomeRoute
  '/checklist/$id': typeof LayoutChecklistIdRoute
  '/daily-checking/$id': typeof LayoutDailyCheckingIdRoute
  '/fm-it/notification': typeof LayoutFmItNotificationRoute
  '/fm-it/ticket-list': typeof LayoutFmItTicketListRoute
  '/lecturer/room-asset-list': typeof LayoutLecturerRoomAssetListRouteWithChildren
  '/room-asset-list/$id': typeof LayoutRoomAssetListIdRoute
  '/ticket/$id': typeof LayoutTicketIdRoute
  '/checklist': typeof LayoutChecklistIndexRoute
  '/scan': typeof LayoutScanIndexRoute
  '/ticket': typeof LayoutTicketIndexRoute
  '/fm-it/ticket-detail/$id': typeof LayoutFmItTicketDetailIdRoute
  '/lecturer/room-asset-list/$id': typeof LayoutLecturerRoomAssetListIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/history': typeof LayoutHistoryRoute
  '/_layout/room-asset-list': typeof LayoutRoomAssetListRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/$module/home': typeof LayoutModuleHomeRoute
  '/_layout/checklist/$id': typeof LayoutChecklistIdRoute
  '/_layout/daily-checking/$id': typeof LayoutDailyCheckingIdRoute
  '/_layout/fm-it/notification': typeof LayoutFmItNotificationRoute
  '/_layout/fm-it/ticket-list': typeof LayoutFmItTicketListRoute
  '/_layout/lecturer/room-asset-list': typeof LayoutLecturerRoomAssetListRouteWithChildren
  '/_layout/room-asset-list/$id': typeof LayoutRoomAssetListIdRoute
  '/_layout/ticket/$id': typeof LayoutTicketIdRoute
  '/_layout/checklist/': typeof LayoutChecklistIndexRoute
  '/_layout/scan/': typeof LayoutScanIndexRoute
  '/_layout/ticket/': typeof LayoutTicketIndexRoute
  '/_layout/fm-it/ticket-detail/$id': typeof LayoutFmItTicketDetailIdRoute
  '/_layout/lecturer/room-asset-list/$id': typeof LayoutLecturerRoomAssetListIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/history'
    | '/room-asset-list'
    | '/$module/home'
    | '/checklist/$id'
    | '/daily-checking/$id'
    | '/fm-it/notification'
    | '/fm-it/ticket-list'
    | '/lecturer/room-asset-list'
    | '/room-asset-list/$id'
    | '/ticket/$id'
    | '/checklist/'
    | '/scan/'
    | '/ticket/'
    | '/fm-it/ticket-detail/$id'
    | '/lecturer/room-asset-list/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/history'
    | '/room-asset-list'
    | '/'
    | '/$module/home'
    | '/checklist/$id'
    | '/daily-checking/$id'
    | '/fm-it/notification'
    | '/fm-it/ticket-list'
    | '/lecturer/room-asset-list'
    | '/room-asset-list/$id'
    | '/ticket/$id'
    | '/checklist'
    | '/scan'
    | '/ticket'
    | '/fm-it/ticket-detail/$id'
    | '/lecturer/room-asset-list/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/history'
    | '/_layout/room-asset-list'
    | '/_layout/'
    | '/_layout/$module/home'
    | '/_layout/checklist/$id'
    | '/_layout/daily-checking/$id'
    | '/_layout/fm-it/notification'
    | '/_layout/fm-it/ticket-list'
    | '/_layout/lecturer/room-asset-list'
    | '/_layout/room-asset-list/$id'
    | '/_layout/ticket/$id'
    | '/_layout/checklist/'
    | '/_layout/scan/'
    | '/_layout/ticket/'
    | '/_layout/fm-it/ticket-detail/$id'
    | '/_layout/lecturer/room-asset-list/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/room-asset-list': {
      id: '/_layout/room-asset-list'
      path: '/room-asset-list'
      fullPath: '/room-asset-list'
      preLoaderRoute: typeof LayoutRoomAssetListRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/history': {
      id: '/_layout/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof LayoutHistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ticket/': {
      id: '/_layout/ticket/'
      path: '/ticket'
      fullPath: '/ticket/'
      preLoaderRoute: typeof LayoutTicketIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/scan/': {
      id: '/_layout/scan/'
      path: '/scan'
      fullPath: '/scan/'
      preLoaderRoute: typeof LayoutScanIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/checklist/': {
      id: '/_layout/checklist/'
      path: '/checklist'
      fullPath: '/checklist/'
      preLoaderRoute: typeof LayoutChecklistIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ticket/$id': {
      id: '/_layout/ticket/$id'
      path: '/ticket/$id'
      fullPath: '/ticket/$id'
      preLoaderRoute: typeof LayoutTicketIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/room-asset-list/$id': {
      id: '/_layout/room-asset-list/$id'
      path: '/$id'
      fullPath: '/room-asset-list/$id'
      preLoaderRoute: typeof LayoutRoomAssetListIdRouteImport
      parentRoute: typeof LayoutRoomAssetListRoute
    }
    '/_layout/lecturer/room-asset-list': {
      id: '/_layout/lecturer/room-asset-list'
      path: '/lecturer/room-asset-list'
      fullPath: '/lecturer/room-asset-list'
      preLoaderRoute: typeof LayoutLecturerRoomAssetListRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fm-it/ticket-list': {
      id: '/_layout/fm-it/ticket-list'
      path: '/fm-it/ticket-list'
      fullPath: '/fm-it/ticket-list'
      preLoaderRoute: typeof LayoutFmItTicketListRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fm-it/notification': {
      id: '/_layout/fm-it/notification'
      path: '/fm-it/notification'
      fullPath: '/fm-it/notification'
      preLoaderRoute: typeof LayoutFmItNotificationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/daily-checking/$id': {
      id: '/_layout/daily-checking/$id'
      path: '/daily-checking/$id'
      fullPath: '/daily-checking/$id'
      preLoaderRoute: typeof LayoutDailyCheckingIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/checklist/$id': {
      id: '/_layout/checklist/$id'
      path: '/checklist/$id'
      fullPath: '/checklist/$id'
      preLoaderRoute: typeof LayoutChecklistIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$module/home': {
      id: '/_layout/$module/home'
      path: '/$module/home'
      fullPath: '/$module/home'
      preLoaderRoute: typeof LayoutModuleHomeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/lecturer/room-asset-list/$id': {
      id: '/_layout/lecturer/room-asset-list/$id'
      path: '/$id'
      fullPath: '/lecturer/room-asset-list/$id'
      preLoaderRoute: typeof LayoutLecturerRoomAssetListIdRouteImport
      parentRoute: typeof LayoutLecturerRoomAssetListRoute
    }
    '/_layout/fm-it/ticket-detail/$id': {
      id: '/_layout/fm-it/ticket-detail/$id'
      path: '/fm-it/ticket-detail/$id'
      fullPath: '/fm-it/ticket-detail/$id'
      preLoaderRoute: typeof LayoutFmItTicketDetailIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRoomAssetListRouteChildren {
  LayoutRoomAssetListIdRoute: typeof LayoutRoomAssetListIdRoute
}

const LayoutRoomAssetListRouteChildren: LayoutRoomAssetListRouteChildren = {
  LayoutRoomAssetListIdRoute: LayoutRoomAssetListIdRoute,
}

const LayoutRoomAssetListRouteWithChildren =
  LayoutRoomAssetListRoute._addFileChildren(LayoutRoomAssetListRouteChildren)

interface LayoutLecturerRoomAssetListRouteChildren {
  LayoutLecturerRoomAssetListIdRoute: typeof LayoutLecturerRoomAssetListIdRoute
}

const LayoutLecturerRoomAssetListRouteChildren: LayoutLecturerRoomAssetListRouteChildren =
  {
    LayoutLecturerRoomAssetListIdRoute: LayoutLecturerRoomAssetListIdRoute,
  }

const LayoutLecturerRoomAssetListRouteWithChildren =
  LayoutLecturerRoomAssetListRoute._addFileChildren(
    LayoutLecturerRoomAssetListRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutHistoryRoute: typeof LayoutHistoryRoute
  LayoutRoomAssetListRoute: typeof LayoutRoomAssetListRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutModuleHomeRoute: typeof LayoutModuleHomeRoute
  LayoutChecklistIdRoute: typeof LayoutChecklistIdRoute
  LayoutDailyCheckingIdRoute: typeof LayoutDailyCheckingIdRoute
  LayoutFmItNotificationRoute: typeof LayoutFmItNotificationRoute
  LayoutFmItTicketListRoute: typeof LayoutFmItTicketListRoute
  LayoutLecturerRoomAssetListRoute: typeof LayoutLecturerRoomAssetListRouteWithChildren
  LayoutTicketIdRoute: typeof LayoutTicketIdRoute
  LayoutChecklistIndexRoute: typeof LayoutChecklistIndexRoute
  LayoutScanIndexRoute: typeof LayoutScanIndexRoute
  LayoutTicketIndexRoute: typeof LayoutTicketIndexRoute
  LayoutFmItTicketDetailIdRoute: typeof LayoutFmItTicketDetailIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutHistoryRoute: LayoutHistoryRoute,
  LayoutRoomAssetListRoute: LayoutRoomAssetListRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutModuleHomeRoute: LayoutModuleHomeRoute,
  LayoutChecklistIdRoute: LayoutChecklistIdRoute,
  LayoutDailyCheckingIdRoute: LayoutDailyCheckingIdRoute,
  LayoutFmItNotificationRoute: LayoutFmItNotificationRoute,
  LayoutFmItTicketListRoute: LayoutFmItTicketListRoute,
  LayoutLecturerRoomAssetListRoute:
    LayoutLecturerRoomAssetListRouteWithChildren,
  LayoutTicketIdRoute: LayoutTicketIdRoute,
  LayoutChecklistIndexRoute: LayoutChecklistIndexRoute,
  LayoutScanIndexRoute: LayoutScanIndexRoute,
  LayoutTicketIndexRoute: LayoutTicketIndexRoute,
  LayoutFmItTicketDetailIdRoute: LayoutFmItTicketDetailIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
